SET(SGI_MAJOR_VERSION 0)
SET(SGI_MINOR_VERSION 3)
SET(SGI_PATCH_VERSION 0)
SET(SGI_BUILD_VERSION )
SET(SGI_SOVERSION 0)
SET(SGI_PLUGIN_DIR "osgPlugins-")

MACRO(SGI_PLUGIN PLUGIN_NAME)
    SET(TARGET_MAJOR_VERSION ${SGI_MAJOR_VERSION})
    SET(TARGET_MINOR_VERSION ${SGI_MINOR_VERSION})
    SET(TARGET_PATCH_VERSION ${SGI_PATCH_VERSION})

    # here we use the command to generate the library
    #not sure if needed, but for plugins only Msvc need the d suffix
    IF(MSVC)
        SET(TARGET_NO_DEBUG_POSTFIX)
    ENDIF(MSVC)

    SET(TARGET_LABEL_PREFIX "SGIPlugin")
    SET(TARGET_NO_IMPORT_LIB 1)
    SET(TARGET_NO_MANIFEST 1)
    SET(TARGET_NO_LIBPREFIX 1)

    SET(TARGET_VERSION ${SGI_VERSION})
    SET(TARGET_SOVERSION ${SGI_SOVERSION})
    SET(TARGET_MAJOR_VERSION ${SGI_MAJOR_VERSION})
    SET(TARGET_MINOR_VERSION ${SGI_MINOR_VERSION})
    SET(TARGET_PATCH_VERSION ${SGI_PATCH_VERSION})
    SET(TARGET_BUILD_VERSION ${SGI_SOVERSION})
    SET(TARGET_PRODUCT_NAME "SGI")
    SET(TARGET_VERSION_RC_INTERNALNAME "SGI")
    SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2012-2015")
    SET(TARGET_NO_TRANSLATION 1)

    SET(SGI_PLUGIN_NAME "${PLUGIN_NAME}")
    string(MD5 _itemtype_offset "${PLUGIN_NAME}")
    string(SUBSTRING "${_itemtype_offset}" 0 6 _itemtype_offset)
    SET(_itemtype_offset "0x${_itemtype_offset}00")

    SET(LIBRARY_OUTPUT_PATH ${LIBRARY_OUTPUT_PATH}/${OSG_PLUGINS})
    MAKE_DIRECTORY(${OUTPUT_LIBDIR})

    LIST(APPEND TARGET_LIBRARIES_VARS OSG_LIBRARY OSGDB_LIBRARY)

    IF(Qt5Widgets_FOUND)
        #QT5_ADD_RESOURCES( LIB_RC_SRCS ${LIB_QT_RCS} )
        QT5_WRAP_UI( TARGET_UI_HDRS ${TARGET_UI} )
        IF(Qt5Widgets_VERSION VERSION_LESS 5.2.0)
            QT5_WRAP_CPP( TARGET_MOC_SRCS ${TARGET_MOC_H} OPTIONS "-f" )
        ELSE()
            QT5_WRAP_CPP( TARGET_UI_SRCS ${TARGET_UI_HDRS} )
            QT5_WRAP_CPP( TARGET_MOC_SRCS ${TARGET_MOC_H} )
        ENDIF()
    ELSE()
        #QT4_ADD_RESOURCES( LIB_RC_SRCS ${LIB_QT_RCS} )
        QT4_WRAP_UI( TARGET_UI_HDRS ${TARGET_UI} )
        QT4_WRAP_CPP( TARGET_MOC_SRCS ${TARGET_MOC_H} OPTIONS "-f" )
    ENDIF()

    INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})

    SET(TARGET_TARGETNAME "osgdb_sgi_${PLUGIN_NAME}_plugin")

    ADD_LIBRARY(${TARGET_TARGETNAME} MODULE ${TARGET_SRC} ${TARGET_H} ${TARGET_MOC_SRCS} ${TARGET_UI_SRCS} ${TARGET_UI_HDRS} )
    SET_TARGET_PROPERTIES(${TARGET_TARGETNAME} PROPERTIES PREFIX "")

    target_compile_definitions(${TARGET_TARGETNAME} PRIVATE
        SGI_PLUGIN_NAME=${PLUGIN_NAME}
        SGI_ITEMTYPE_OFFSET=${_itemtype_offset})
    
    SETUP_LINK_LIBRARIES()

ENDMACRO(SGI_PLUGIN)
